name: CI workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lab 01_running_tests_with_nose
        run: |
          cd labs/01_running_tests_with_nose
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=triangle

      - name: Run Lab 02_writing_test_assertions
        run: |
          cd labs/02_writing_test_assertions
          nosetests

      - name: Run Lab 03_test_fixtures
        run: |
          cd labs/03_test_fixtures
          nosetests

      - name: Run Lab 04_test_coverage
        run: |
          cd labs/04_test_coverage
          nosetests
          cd ..

      - name: Run Lab 05_factories_and_fakes
        run: |
          cd labs/05_factories_and_fakes
          nosetests
          cd ..

      - name: Run Lab 06_mocking_objects
        run: |
          cd labs/06_mocking_objects
          nosetests
          cd ..

      - name: Run Lab 07_practicing_tdd
        run: |
          cd labs/07_practicing_tdd
          nosetests
          cd ..

      - name: Install dependencies Behave
        run: |
          cd labs/08_environment_setup
          pip install -r requirements.txt

      - name: Run Lab 08_environment_setup
        run: |
          cd labs/08_environment_setup
          behave
          cd ..

      - name: Run Lab 10_loading_test_data
        run: |
          cd labs/10_loading_test_data
          behave
          cd ..

      - name: Run Lab 11_generating_steps
        run: |
          cd labs/11_generating_steps
          behave
          cd ..

      - name: Run Lab 12_implementing_steps
        run: |
          cd labs/12_implementing_steps
          behave
          cd ..

      - name: Run Lab 13_variable_substitution
        run: |
          cd labs/13_variable_substitution
          behave
          cd ..
