name: CI workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lab 01
        run: |
          cd labs/01_running_tests_with_nose
          nosetests -v --with-spec --spec-color --with-coverage --cover-package=triangle
          cd ..

      - name: Run Lab 02
        run: |
          cd 02_writing_test_assertions
          nosetests
          cd ..

      - name: Run Lab 03
        run: |
          cd 03_test_fixtures
          nosetests
          cd ..

      - name: Run Lab 04
        run: |
          cd 04_test_coverage
          nosetests
          cd ..
