name: CI workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lab 01
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=triangle labs/01_running_tests_with_nose/test_triangle.py

      - name: Run Lab 02
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=stack labs/02_writing_test_assertions/test_stack.py

